config/routes.rb
Polisoms::Application.routes.draw do

  match '/search', to: 'search#search'
  

  # match '/choose_district' => 'appointments#choose_district'
  # match '/choose_hospital' => 'appointments#choose_hospital'
  # match '/check_patient' => 'appointments#check_patient'
  # match '/get_speciality_list' => 'appointments#get_speciality_list'
  # match '/get_doctor_list' => 'appointments#get_doctor_list'
  # match '/get_available_dates' => 'appointments#get_available_dates'
  # match '/get_available_appointments' => 'appointments#get_available_appointments'
  # match '/set_appointment' => 'appointments#set_appointment'
  # match '/get_patient_history' => 'appointments#get_patient_history'
  # match '/create_claim_for_refusal' => 'appointments#create_claim_for_refusal'


  scope 'api' do
    # раздел запись к врачу
    get 'districts' => 'api_appointments#districts'
    get 'polyclinics' => 'api_appointments#polyclinics'
    get 'specialities' => 'api_appointments#specialities'
    get 'doctors' => 'api_appointments#doctors'
    # ======================
  end

  namespace :api do
    resources :reviews, only: [:create, :index]
  end



  # публичные страницы с записью к врачу
  get '/appointment/step1' => 'appointments#step1', as: :appointment_step1
  match '/appointment/step2' => 'appointments#step2', as: :appointment_step2
  match '/appointment/step3' => 'appointments#step3', as: :appointment_step3
  match '/appointment/step4' => 'appointments#step4', as: :appointment_step4
  match '/appointment/check' => 'appointments#check', as: :appointment_check
  match '/appointment/confirm' => 'appointments#confirm', as: :appointment_confirm
  match '/appointment/history' => 'appointments#history', as: :appointment_history

  # публичные страницы на отмену записи к врачу
  get '/cancel_appointment/step1' => 'cancel_appointments#step1', as: :cancel_appointment_step1
  match '/cancel_appointment/step2' => 'cancel_appointments#step2', as: :cancel_appointment_step2
  match '/cancel_appointment/history' => 'cancel_appointments#history', as: :cancel_appointment_history
  match '/cancel_appointment/auth' => 'cancel_appointments#passport_auth', as: :cancel_appointment_auth
  match '/cancel_appointment/claim_for_refusal' => 'cancel_appointments#claim_for_refusal', as: :cancel_appointment_claim_for_refusal

  # публичные страницы для вызова врача на дом
  get '/doctor_requests/person' => 'doctor_requests#person', as: :doctor_requests_person
  match '/doctor_requests/hospital' => 'doctor_requests#hospital', as: :doctor_requests_hospital
  match '/doctor_requests/form' => 'doctor_requests#form', as: :doctor_requests_form
  post '/doctor_requests/create' => 'doctor_requests#create', as: :doctor_requests
  get '/doctor_requests/success' => 'doctor_requests#success', as: :doctor_requests_success
  get '/doctor_requests/apology' => 'doctor_requests#apology', as: :doctor_requests_apology
  get '/doctor_requests/rostovskaya_all_live' => 'doctor_requests#all_live', as: :doctor_requests_all_live
  get '/doctor_requests/list' => 'doctor_requests#list', as: :doctor_requests_list
  put '/doctor_requests/:id' => 'doctor_requests#update', as: :doctor_request
  get '/doctor_requests/:check_free_coupons' => 'doctor_requests#check_free_coupons', as: :doctor_request_check_free_coupons


  resources :reviews, only: [:index, :create]
  resources :articles
  
  match '/load_articles' => 'articles#index'
  
  resources :services


  mount Ckeditor::Engine => '/ckeditor'

  resources :abouts

  resources :offices

  # admin area
  ActiveAdmin.routes(self)
  post '/admin/reviews/:id/answer' => 'admin/reviews#answer', as: :admin_review_review_answers
  # =================

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root :to => 'static_pages#home'
  get 'poll_of_the_year' => 'static_pages#poll_of_the_year', as: :poll_of_the_year
  get 'jci' => 'static_pages#jci', as: :jci
  # страница с марафоном и записью к врачу по 4ое июля
  # get 'runners' => 'static_pages#runners', as: :runners
  get 'polls/:id' => 'static_pages#polls'
  get 'p/:id' => 'static_pages#external_poll', as: :external_poll

  resources :news

  post 'set_region', to: 'application#set_region'
  post 'update_office', to: 'offices#update_pos'

  resources :doctors, only: [:index, :show], as: :staff do
    member do
      post 'like'
    end
  end

  resources :vacancies, only: [:index, :show]
  resource :vacancy_requests, only: [:create]
  resource :visit_requests, only: [:create]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @review = Review.new
    @articles = Article.joins(:office).where('offices.region_id=?', current_region.id).order('created_at DESC').limit(3)
    @slides = Slide.where(region_id: current_region.id).order('position ASC')
  end
  
  def appointment
    @other = Article.limit(3)
  end

  def poll_of_the_year
  end

  def jci
  end

  # страница с марафоном и записью к врачу по 4ое июля
  # def runners
  #   @visit_request = VisitRequest.new
  # end

  def polls
    @id = params[:id]
    @iframe_path = "http://polismobile0.1gb.ru?idRecord=#{@id}"
  end

  def external_poll
    @poll = ExternalPoll.where(id: params[:id]).first
    if @poll.try(:active)
      @iframe_path = @poll.url
    else
      redirect_to '/404'
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_custom_banner.html.slim
div#slider
  ul
    li
      = link_to runners_path do
        = image_tag 'banners/runners.jpg'

app/views/static_pages/_slider.html.erb
<div id="slider">
  <ul>
    <li>
      <%= link_to 'https://www.rosminzdrav.ru/news/2016/12/05/3315-v-ramkah-otkrytiya-rossiyskoy-nedeli-zdravoohraneniya-2016-ob-yavleny-pobediteli-vserossiyskogo-konkursa-luchshiy-proekt-gosudarstvenno-chastnogo-vzaimodeystviya-v-zdravoohranenii', target: '_blank' do %>
        <%= image_tag 'best-public-health-2016.png' %>
      <% end %>
    </li>
    <li>
      <%= link_to 'http://spb.awards.rbc.ru/nominees/euromed-group-spb.htm', target: '_blank' do %>
        <%= image_tag 'rbk-slide.png' %>
      <% end %>
    </li>
    <% @slides.each do |slide| %>
      <li>
        <%= image_tag slide.image.url(:content) %>
        <div class="s-text-wrap">
          <span class="sw-title"><%= slide.title %></span>

          <div class="sw-text"><%= simple_format slide.text %></div>
          <%= link_to slide.link_title, slide.link_url, :class => 'sw-detail' %>
        </div>
      </li>
    <% end %>
  </ul>
  <span class="s-bordered-layer"></span>

  <div class="start__bottom clearfix review-button__container">
    <div class="review-button__inline">
      <%= react_component('ReviewButton', { \
            offices: offices_for_review, \
            doctors: doctors_for_review, \
            }, { prerender: true })
        %>
    </div>
    <div class="review-button__inline">
      <%= react_component('ReviewButton', { \
            type: 'negative', \
            offices: offices_for_review, \
            doctors: doctors_for_review, \
            }, { prerender: true })
        %>
    </div>
    
  </div>

  <div id="s-pagination"></div>
</div>

app/views/static_pages/_visit_request_form.html.slim
.vacancy-request-form
  hr
  br
  = form_for request do |f|

    .vacancy-request-form__label ФИО
    .vacancy-request-form__input
      = f.text_field :name, placeholder: 'Иван Иванов', maxlength: 249, size: 40, required: true
    .vacancy-request-form__label Дата рождения
    .vacancy-request-form__input
      = f.text_field :birthday, placeholder: '28 февраля 1987', maxlength: 249, size: 40, required: true
    .vacancy-request-form__label Телефон
    .vacancy-request-form__input
      = f.text_field :phone, placeholder: '+7 987 654-32-10', maxlength: 249, size: 40, required: true
    .vacancy-request-form__label Электронная почта
    .vacancy-request-form__input
      = f.text_field :email, placeholder: 'name@mail.ru', maxlength: 249, size: 40

    = f.button 'Отправить заявку', class: 'vacancy-request-form__submit'

app/views/static_pages/_widget.html.erb
<div id="test"></div>
		<script type="text/javascript">
			window.zdravWidget = {
				id: document.getElementById("test"),
				TOKEN: "abcd"
			};
		</script>
		<script src="/poliswdgt.js" charset="UTF-8"></script>

app/views/static_pages/appointment.html.erb
<div class="body clearfix">
		<!-- data left -->		
		<div class="body__data-left">
			<div class="newsdata">
				<a name="top"></a>
				<div class="clearfix"><a href="javascript:history.back()" class="newsdata__back">назад</a></div>
				<%= render 'widget' %>
			</div>			
		</div>
	</div>

app/views/static_pages/external_poll.slim
.body.clearfix(style="min-height: 500px;")
  iframe(src=@iframe_path height="500px" width="100%" style="border: none;")

app/views/static_pages/home.html.erb
<%= render 'slider' %>
<%# render 'custom_banner' %>

<% content_for :head do %>
<script type="text/javascript">
$(document).ready(function(){
	$("#slider ul").carouFredSel({
		auto: {timeoutDuration: 5000},
   	pagination: "#s-pagination"
	});
});
</script>
<% end %>

<div class="body clearfix">
	<p class="start__text">Полис — это ваш личный участковый врач, такой же, как в государственной поликлинике.<br/> Обратиться за медицинской помощью к нему вы можете абсолютно бесплатно. Прямо сейчас.</p>
	<ul class="start__faq clearfix">
		<li>
			<span>что взять с собой на прием?</span>
			<%= link_to "abouts#what_to_take" do %>
			Документы, которые вам понадобятся <br/>для визита к врачу
			<% end %>
		</li>
		<li>
			<span>Как записаться на прием?</span>
			<%= link_to "abouts#how_to_join" do %>
			Есть 3 удобных способа сообщить <br/>нам о своем визите
			<% end %>
		</li>
		<li class="start__faq-item-last">
			<span>Нет полиса ОМС?</span>
			<%= link_to "services#about_polis" do %>
			Получите его у нас
			<% end %>
		</li>
	</ul>
	
	<div class="start__news">
		<h3 class="start__news-title">Новости</h3>
		<ul class="clearfix">
				<% @articles.each do |article| %>
			    <li><%= link_to article.title, article %>
				<p><%= truncate(strip_tags(article.description), length: 200).html_safe %></p></li>
				<% end %>
		</ul>
		<%= link_to "все новости", articles_path, :class => 'start__news-all' %>
	</div>
</div>

<%# render 'reviews/review' %>
<%# render 'reviews/thank' %>

app/views/static_pages/jci.slim
.body.clearfix(style="min-height: 500px;")
  .text__title Мы готовимся к аккредитации по стандарту JCI

  = image_tag 'jci-page-doctors.png'

  p.text__part
    br
    b JCI (Joint Commission International)
    ' – одна из самых крупных международных организаций в мире, которая выступает экспертом в оценке качества и безопасности работы медицинских организаций.
  p.text__part
    ' Стандарты JCI разрабатываются международными экспертами, и считаются «золотым стандартом» в области здравоохранения.
  p.text__part
    | Аккредитация  JCI не является обязательной, однако стремление получить данный сертификат соответствия всегда означает серьезное отношение администрации к принятым обязательствам перед пациентами.
  p.text__part
    | Внедрение стандартов JCI помогает повысить уровень культуры работы, снизить риск, как для пациентов, так и для сотрудников организации и повысить качество и безопасность медицинской помощи.

  p.text__part
    br
    b Контакты JCI (Joint Commission International):

  p.text__part
    | 1515 West 22nd Street, Suite 1300W Oak Brook, Illinois 60523 USA

  p.text__part
    = link_to '+1 630 268 7400', 'tel:+1 630 268 7400'
    '  (с 8:30 до 17:00, с понедельника по пятницу)

  p.text__part
    = link_to 'www.jointcommissioninternational.org', '//www.jointcommissioninternational.org'
  br
  br

app/views/static_pages/poll_of_the_year.html.slim
.body.clearfix(style="min-height: 500px;")
  .text__title Дорогие друзья
  p.text__tizer
    | Компания «Полис. Участковые врачи», которая работает для вас, была отмечена главным деловым СМИ страны – РБК, и выдвинута на премию в номинации «Прорыв года».

  = image_tag 'rbk_poll_of_year.jpg'

  p.text__part
    | Если вы неравнодушны к нашей работе, пожалуйста, примите участие в голосовании, которое будет проходить с 7 по 15 ноября.
    br
    ' Для этого нужно зарегестироваться на сайте
    = link_to 'spb.awards.rbc.ru', 'http://spb.awards.rbc.ru/nominees/breakthrough_spb/euromed-group-spb.htm'
    br
    | и отдать свой голос за Euromed Group – группу компаний, в которую входит наш «Полис».

    br
    br
    br
    = link_to 'http://spb.awards.rbc.ru/nominees/breakthrough_spb/euromed-group-spb.htm' do
      = image_tag 'to_poll_button.png'
    br
    br
    br
  .text__title Давайте станем прорывом года вместе

app/views/static_pages/polls.html.slim
.body.clearfix(style="min-height: 500px;")
  iframe(src=@iframe_path height="500px" width="100%" style="border: none;")

app/views/static_pages/runners.html.slim
.body.clearfix(style="min-height: 500px;")
  .text__title Дорогие друзья!
  p.text__part
    | 3 июля 2016 года в Санкт-Петербурге состоится традиционный Международный марафон «Белые ночи».
    br
    br
    | Забег пройдет в центре города на дистанции 42 км 195 м и 10 км.
    br
    br
    | Участникам необходимо пройти медицинский осмотр и в день проведения марафона иметь справку о допуске к соревнованиям.

  = image_tag 'pages/runners/importnant.png', class: 'text__image'

  p.text__tizer
    | Все желающие могут быстро и совершенно бесплатно пройти этот осмотр в любом из центров «Полис», расположенных по адресам:

  p.text__tizer
    | Приморский район:
  p.text__part.m-glue
    | · пр. Королева, д.63 к.2
    br
    | · ул. Малая Десятинная д.11-1, лит. А
    br
    | · ул. Парашютная, д. 23 к.2
    br
    | · ул. Савушкина, д. 138
    br
    | · Приморский пр., д. 137, к.1
    br
    | · Фермское шоссе, д.32
    br
    | · Коломяжский пр., д. 20
    br
    | · Ул. Оптиков д. 52 лит В

  p.text__tizer
    | Красносельский район:
  p.text__part.m-glue
    | · Красносельское шоссе, д. 56, к.2
    br
    | · Петергофское шоссе, д.59, лит.А
    br
    | · ул. Политрука Пасечника д. 8

  p.text__tizer
    | Пушкинский район:
  p.text__part.m-glue
    | · Московское шоссе, д. 246


  p.text__tizer
    | Выборгский район:
  p.text__part.m-glue
    | · Школьный переулок д. 1 литера Б
    br
    | · ул. Федора Абрамова дом 8


  p.text__tizer
    | Красногвардейский район:
  p.text__part.m-glue
    | · Муринская дорога д. 74 кор. 1


  p.text__tizer
    | Просто возьмите с собой паспорт, полис ОМС и скажите кодовое слово «Марафон»
    ' администратору центра на регистратуре!
  /TODO: сделать класс у кнопки нормальный, какой-нить общий для всего продукта в целом
  p.text__part
    = button_tag class: 'text__imagable-btn js-open-request-form' do
      = image_tag 'pages/runners/action.png'
    .vacancy-request-form__help = flash[:notice]
    .js-request-form(style='display:none;')
      = render 'static_pages/visit_request_form', request: @visit_request

  br
  br
  br
  br
  p.text__part
    span = "Хотите узнать подробнее? Пишите нам вконтакте "
    = link_to 'vk.com/polis_oms', '//vk.com/polis_oms', target: :blank

app/views/static_pages/vacancies.html.slim
.body.clearfix(style="min-height: 500px;")
  - email = current_region.id == 1 ? 'HR@polisoms.ru' : 'ul-admin@polisoms.ru'
  - phone = current_region.id == 1 ? '670-00-30' : '30-70-03'
  h1.text__title Наши вакансии
  .responses
    p
      strong
        'Сеть медицинский центров Полис. Участковые врачи активно растет и&nbsp;развивается.
        br
        'Нам очень нужны настоящие профессионалы и&nbsp;просто хорошие люди, которые любят людей.
    br
    p
      'Об&nbsp;открытых вакансиях вы&nbsp;можете узнать по&nbsp;номеру:
      strong = phone
    br
    p
      'Резюме отправляйте на&nbsp;адрес электронной почты
      = link_to email, "mailto:#{email}"