config/routes.rb
Polisoms::Application.routes.draw do

  match '/search', to: 'search#search'
  

  # match '/choose_district' => 'appointments#choose_district'
  # match '/choose_hospital' => 'appointments#choose_hospital'
  # match '/check_patient' => 'appointments#check_patient'
  # match '/get_speciality_list' => 'appointments#get_speciality_list'
  # match '/get_doctor_list' => 'appointments#get_doctor_list'
  # match '/get_available_dates' => 'appointments#get_available_dates'
  # match '/get_available_appointments' => 'appointments#get_available_appointments'
  # match '/set_appointment' => 'appointments#set_appointment'
  # match '/get_patient_history' => 'appointments#get_patient_history'
  # match '/create_claim_for_refusal' => 'appointments#create_claim_for_refusal'


  scope 'api' do
    # раздел запись к врачу
    get 'districts' => 'api_appointments#districts'
    get 'polyclinics' => 'api_appointments#polyclinics'
    get 'specialities' => 'api_appointments#specialities'
    get 'doctors' => 'api_appointments#doctors'
    # ======================
  end

  namespace :api do
    resources :reviews, only: [:create, :index]
  end



  # публичные страницы с записью к врачу
  get '/appointment/step1' => 'appointments#step1', as: :appointment_step1
  match '/appointment/step2' => 'appointments#step2', as: :appointment_step2
  match '/appointment/step3' => 'appointments#step3', as: :appointment_step3
  match '/appointment/step4' => 'appointments#step4', as: :appointment_step4
  match '/appointment/check' => 'appointments#check', as: :appointment_check
  match '/appointment/confirm' => 'appointments#confirm', as: :appointment_confirm
  match '/appointment/history' => 'appointments#history', as: :appointment_history

  # публичные страницы на отмену записи к врачу
  get '/cancel_appointment/step1' => 'cancel_appointments#step1', as: :cancel_appointment_step1
  match '/cancel_appointment/step2' => 'cancel_appointments#step2', as: :cancel_appointment_step2
  match '/cancel_appointment/history' => 'cancel_appointments#history', as: :cancel_appointment_history
  match '/cancel_appointment/auth' => 'cancel_appointments#passport_auth', as: :cancel_appointment_auth
  match '/cancel_appointment/claim_for_refusal' => 'cancel_appointments#claim_for_refusal', as: :cancel_appointment_claim_for_refusal

  # публичные страницы для вызова врача на дом
  get '/doctor_requests/person' => 'doctor_requests#person', as: :doctor_requests_person
  match '/doctor_requests/hospital' => 'doctor_requests#hospital', as: :doctor_requests_hospital
  match '/doctor_requests/form' => 'doctor_requests#form', as: :doctor_requests_form
  post '/doctor_requests/create' => 'doctor_requests#create', as: :doctor_requests
  get '/doctor_requests/success' => 'doctor_requests#success', as: :doctor_requests_success
  get '/doctor_requests/apology' => 'doctor_requests#apology', as: :doctor_requests_apology
  get '/doctor_requests/rostovskaya_all_live' => 'doctor_requests#all_live', as: :doctor_requests_all_live
  get '/doctor_requests/list' => 'doctor_requests#list', as: :doctor_requests_list
  put '/doctor_requests/:id' => 'doctor_requests#update', as: :doctor_request
  get '/doctor_requests/:check_free_coupons' => 'doctor_requests#check_free_coupons', as: :doctor_request_check_free_coupons


  resources :reviews, only: [:index, :create]
  resources :articles
  
  match '/load_articles' => 'articles#index'
  
  resources :services


  mount Ckeditor::Engine => '/ckeditor'

  resources :abouts

  resources :offices

  # admin area
  ActiveAdmin.routes(self)
  post '/admin/reviews/:id/answer' => 'admin/reviews#answer', as: :admin_review_review_answers
  # =================

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root :to => 'static_pages#home'
  get 'poll_of_the_year' => 'static_pages#poll_of_the_year', as: :poll_of_the_year
  get 'jci' => 'static_pages#jci', as: :jci
  # страница с марафоном и записью к врачу по 4ое июля
  # get 'runners' => 'static_pages#runners', as: :runners
  get 'polls/:id' => 'static_pages#polls'
  get 'p/:id' => 'static_pages#external_poll', as: :external_poll

  resources :news

  post 'set_region', to: 'application#set_region'
  post 'update_office', to: 'offices#update_pos'

  resources :doctors, only: [:index, :show], as: :staff do
    member do
      post 'like'
    end
  end

  resources :vacancies, only: [:index, :show]
  resource :vacancy_requests, only: [:create]
  resource :visit_requests, only: [:create]
end

app/models/doctor_request.rb
class DoctorRequest < ActiveRecord::Base
  attr_accessible :full_name,
                  :birthday,
                  :address,
                  :phone_number,
                  :additional_phone_number,
                  :visit_at,
                  :department_id,
                  :department_name,
                  :region_id,
                  :region_name,
                  :called,
                  :comment

end

app/controllers/doctor_requests_controller.rb
# encoding: utf-8
class DoctorRequestsController < ApplicationController
  before_filter :create_appointment, except: [:list, :update]
  before_filter :check_requests_time, only: :form

  http_basic_authenticate_with name: "polisoms", password: "temporarysection", only: :list

  def list
    @filtered_date = process_filtered_date
    filtered_date_start = @filtered_date.beginning_of_day
    filtered_date_end = @filtered_date.end_of_day
    @doctor_requests = DoctorRequest
                           .order('created_at DESC')
                           .where('created_at >= ?', filtered_date_start)
                           .where('created_at < ?', filtered_date_end)

    render layout: false
  end

  def update
    @request = DoctorRequest.find(params[:id])
    @request.update_attributes(params[:doctor_request])
    render json: @request
  end

  def person
    @district_collection = CallDoctorHomeDistrictTime.order(district_title: :asc)
    @show_districts_info = @district_collection.present?
  end

  def hospital
    params.delete(:action)
    @back_path = doctor_requests_person_path(params)
  end

  # валидируем пациента и в случае успеха показываем третий шаг
  def form
    begin
      init_birthday
      params.delete(:action)
      @back_path = doctor_requests_hospital_path(params)
      patient = @appointment.check_patient(params[:lpu_id], params[:first_name], params[:last_name], params[:birthday])
      if patient.blank?
        flash[:error] = 'Пациент с введенными значениями не найден'
        redirect_to doctor_requests_person_path(params)
      else
        params[:patient_id] = patient
      end
    rescue Savon::SOAPFault, ArgumentError, TypeError
      flash[:error] = 'Введенные ранее данные устарели, пожалуйста, начните с начала'
      redirect_to doctor_requests_person_path(params)
    end
  end


  def create
    begin
      requestData = {
        visit_at: visit_at,
        birthday: Date.new(params['birthday(1i)'].to_i, params['birthday(2i)'].to_i, params['birthday(3i)'].to_i),
        full_name: "#{params[:last_name]} #{params[:first_name]} #{params[:middle_name]}",
        address: params[:address],
        phone_number: params[:phone_number],
        additional_phone_number: params[:additional_phone_number],
        department_name: params[:lpu_title],
        department_id: params[:lpu_id],
        region_id: params[:district_id]
      }

      DoctorRequest.create(requestData)
      CallDoctorHomeCouponRequest.new({lpu_id: params[:lpu_id], patient_id: params[:patient_id]}).save!
      redirect_to doctor_requests_success_path(params)
    rescue Exception => e
      puts 'ERROR'
      puts e
      flash[:error] = 'При создании заявки произошла ошибка, пожалуйста, начните с начала'
      redirect_to doctor_requests_person_path(params)
    end
  end

  def apology
    @resource = CallDoctorHomeDistrictTime.where(district_id: params[:district_id].to_s).first
  end

  def all_live
    render 'rostovskaya_all_live'
  end

  def check_free_coupons
    render json: CallDoctorHomeCouponsMediator.new(params[:lpu_id]).check_free_coupons
  end

  private

  def check_requests_time
    is_rostovskaya = params[:district_id].to_s == '16' && params[:lpu_id].to_s == '763'
    redirect_to doctor_requests_all_live_path(params) if is_rostovskaya

    @district_time = CallDoctorHomeDistrictTime.where(district_id: params[:district_id].to_s).first
    if @district_time && !@district_time.can_call_home?
      redirect_to doctor_requests_apology_path(params)
    end

  end

  def process_filtered_date
    date = DateTime.now
    if params[:filtered_date]
      begin
        date = Date.new *params[:filtered_date].each.map { |key, value| value.to_i }.reverse
      rescue
        date = DateTime.now
      end
    end
    date
  end

  def create_appointment
    @appointment = Appointment.new
  end


  def init_birthday
    params[:birthday] = unless params['birthday(1i)'].blank? && params['birthday(2i)'].blank? && params['birthday(3i)'].blank?
                          "#{params['birthday(1i)']}-#{params['birthday(2i)']}-#{params['birthday(3i)']}"
                        else
                          nil
                        end
  end


  def init_doctor
    @doctor ||= @appointment.get_doctor_list(params[:speciality_id], params[:lpu_id], params[:patient_id]).select { |d| d[:id_doc] == params[:doctor_id].to_s }.first
  end

  def init_test_params
    params[:district_id] ||= '15'
    params[:lpu_id] ||= '430'
    params[:lpu_title] ||= '__lpu '
    params[:first_name] ||= 'Минеев'
    params[:last_name] ||= 'Виталий'
    params[:middle_name] ||= 'Васильевич'
    params['birthday(3i)'] ||= '07'
    params['birthday(2i)_month'] ||= '10'
    params['birthday(1i)'] ||= '1988'
    params[:birthday] ||= "#{params['birthday(1i)']}-#{params['birthday(2i)_month']}-#{params['birthday(3i)']}"
    params[:speciality_id] ||= '1'
    params[:patient_id] ||= '265335'
    params[:doctor_id] ||= '4'
    params[:doctor_name] ||= '__doctor-name'
    params[:visit_start] ||= Date.today.beginning_of_month.strftime('%Y-%m-%d')
    params[:visit_end] ||= Date.today.end_of_month.strftime('%Y-%m-%d')
    params[:appointment_id] ||= 1
    params[:visit_time] ||= '__17:00'
    params[:visit_date] ||= '__2014-01-01'
  end

  def visit_at
    year = params['visitAt(1i)']
    month = params['visitAt(2i)']
    day = params['visitAt(3i)']
    if year.present? && month.present? && day.present?
      DateTime.new(year.to_i, month.to_i, day.to_i).at_beginning_of_day
    else
      DateTime.now.at_beginning_of_day
    end
  end

end

app/helpers/doctor_requests_helper.rb
# coding: utf-8
module DoctorRequestsHelper


  # рисуем последовательност из 3х шагов
  # и выделем цветом шаг по значению переменной num
  # в методе очень важна последовательность блоков
  # т.к.некоторые методы имеют свойство float
  # для позиционирования на странице
  def render_doctor_requests_steps_for_step num=1

    step1_css = 'm-active' if num >= 1
    step2_css = 'm-active' if num >= 2
    step3_css = 'm-active' if num >= 3

    content_tag(:div, class: 'steps') do
      content_tag(:div, '01. Личные данные', class: "step left #{step1_css}") +
      content_tag(:div, '03. Время визита', class: "step right #{step3_css}") +
      content_tag(:div, '02. Ближайшее отделение', class: "step center #{step2_css}")
    end +
    back_button

  end


  # кнопка «назад»
  def back_button
    content_tag :div, class: 'back-btn js-back-btn' do
      link_to('← Назад', @back_path, class: 'link') if @back_path
    end
  end

  def error_messages
    unless flash[:error].blank?
      content_tag :div, flash[:error], class: 'error'
    end
  end

  private


end

app/views/doctor_requests/_hidden_fields.html.slim
.js-hidden-fields
  = hidden_field_tag :district_id, params[:district_id]
  = hidden_field_tag :lpu_id, params[:lpu_id]

  = hidden_field_tag :lpu_title, params[:lpu_title]

  = hidden_field_tag :first_name, params[:first_name]
  = hidden_field_tag :last_name, params[:last_name]
  = hidden_field_tag :middle_name, params[:middle_name]

  = hidden_field_tag 'birthday(3i)', params['birthday(3i)']
  = hidden_field_tag 'birthday(2i)', params['birthday(2i)']
  = hidden_field_tag 'birthday(1i)', params['birthday(1i)']
  = hidden_field_tag :birthday, params[:birthday]

  = hidden_field_tag :address, params[:address]
  = hidden_field_tag :phone_number, params[:phone_number]
  = hidden_field_tag :additional_phone_number, params[:additional_phone_number]
  = hidden_field_tag 'visitAt(3i)', params['visitAt(3i)']
  = hidden_field_tag 'visitAt(2i)', params['visitAt(2i)']
  = hidden_field_tag 'visitAt(1i)', params['visitAt(1i)']
  = hidden_field_tag :visitAt, params[:visitAt]
  /= hidden_field_tag :speciality_id, params[:speciality_id]
  /= hidden_field_tag :patient_id, params[:patient_id]

  /= hidden_field_tag :doctor_id, params[:doctor_id]
  /= hidden_field_tag :doctor_name, params[:doctor_name]

  /= hidden_field_tag :visit_start, params[:visit_start]
  /= hidden_field_tag :visit_end, params[:visit_end]

  /= hidden_field_tag :visit_date, params[:visit_date]
  /= hidden_field_tag :visit_time, params[:visit_time]

  /= hidden_field_tag :appointment_id, params[:appointment_id]

app/views/doctor_requests/apology.html.slim
.body
  .appointment-form.js-appointment-step-6
    .back-btn.js-back-btn

    .col.col-60
      h3 = "Уважаемый #{params[:first_name]} #{params[:middle_name]}"


      .confirm-box
        .form-group
          .text-row
            .info.m-big
              = raw @resource.end_call_home_time_text

app/views/doctor_requests/form.slim
.body
  .appointment-form.js-doctor-requests-form
    = render_doctor_requests_steps_for_step 3

    = error_messages
    = form_tag doctor_requests_path do
      = render 'hidden_fields'
      .form-group
        h3 Время и адрес вызова врача

        p
          | Введите дату вызова врача на дом
          br
          | Cегодня
        /.text-row
          = text_field_tag 'visitAt(3i)', params['visitAt(3i)'], size: '4', placeholder: 'День', required: true, type: 'text', maxlength: 2, class: 'js-numeric'

          - unless params[:visitAt].blank?
            - if Date.valid_date? *params[:visitAt].split('-').map(&:to_i)
              - birthday_month = Date.parse(params[:visitAt])
          - else
            - birthday_month = nil
          = select_month birthday_month, { field_name: false, prompt: 'Месяц', prefix: 'visitAt(2i)', discard_type: true }, { class: 'js-requried  js-select', required: true, placeholder: 'месяц' }

          = text_field_tag 'visitAt(1i)', params['visitAt(1i)'], size: '10', placeholder: 'Год', required: true, type: 'text', maxlength: 4, class: 'js-numeric'

        br
        p Ваш адрес проживания
        .text-row
          = text_area_tag 'address', params[:address], rows: 3, cols: 80, placeholder: '', required: true

        p Контактные данные по которым с вами можно связаться
        .text-row
          = text_field_tag 'phone_number', params[:phone_number], size: '30', placeholder: 'Телефон', required: true
          = text_field_tag 'additional_phone_number', params[:additional_phone_number], size: '40', placeholder: 'Дополнительные телефон'

        br
        p Уважаемые пациенты! Обращаем Ваше внимание, что если контактный номер телефона указан неверно или на звонок оператора никто не ответит, заявка будет считаться недействительной и вызов осуществлен не будет!

      .btn-block
        = submit_tag 'Отправить заявку', class: 'btn btn-success m-inactive js-next-step', disabled: :disabled
        .info Заполните все поля,чтобы перейти к следующему шагу

app/views/doctor_requests/hospital.slim
.body
  .appointment-form.js-call-doctor-home-step-1
    = render_doctor_requests_steps_for_step 2

    = error_messages

    = form_tag doctor_requests_form_path do
      = render 'hidden_fields'

      .form-group
        h3 Уточните Ваш район
        p Выберите из списка район, в котором находится клиника
        = text_field_tag :district_id, params[:district_id], id:'js-districts', size:'50', placeholder: 'Выберите из списка'



      .form-group
        h3 Уточните Вашу клинику
        p Выберите из списка клинику, в которую собираетесь записаться
        = text_field_tag :lpu_id, params[:polyclinic_id], id:'js-polyclinics', size:'90', placeholder: 'Сначала выберите район'

      .confirm-box#js-call-doctor-home-coupons-success-container
        .form-group
          .text-row
            .info
              ' Количество свободных талонов вызова врача на дом:
              span#js-call-doctor-home-free-coupons

      .confirm-box#js-call-doctor-home-coupons-failed-container
        .form-group
          .text-row
            .info
              p Сервис вызова врачей на дом перегружен.
              p В случае экстренной ситуации во избежание длительного ожидания рекомендуем обратиться в службу неотложной помощи или посетить ближайший центр Полис Euromed Group.
              p
                ' Телефоны неотложной помощи в Вашем районе можно уточнить при переходе по ссылке:
                = link_to 'http://gov.spb.ru/helper/zdrav/telefony-rajonnyh-otdelenij-skoroj-pomoshi-pri-poliklinikah/', 'http://gov.spb.ru/helper/zdrav/telefony-rajonnyh-otdelenij-skoroj-pomoshi-pri-poliklinikah/', target: '_blank'
              br
              p Приносим извинения за доставленные неудобства.

      .btn-block
        = submit_tag 'Далее', class: 'btn btn-success m-inactive js-next-step', disabled: :disabled
        .info Заполните все поля,чтобы перейти к следующему шагу

app/views/doctor_requests/list.slim
= csrf_meta_tags
script(src="https://code.jquery.com/jquery-2.2.0.min.js")
css:
  table {
    width: 100%;
  }

  td, th{
    border: 1px solid #eee;
  }


javascript:
  $(document).ready( function(){

    $.ajaxSetup({
      headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      }
    });

    $('.js-called-checkbox').change( function(e){
      var $form = $(this).parent();
      $.ajax($form.attr('action'), {
        data: $form.serializeArray(),
        method: 'PUT'
      });
    });

    var commentTimerId = 0;
    $('.js-comment').keyup( function(e){
      clearTimeout(commentTimerId);
      commentTimerId = setTimeout(function(){
        var $form = $(this).parent();
        $.ajax($form.attr('action'), {
          data: $form.serializeArray(),
          method: 'PUT'
        });
      }.bind(this), 700);
    })

  });


= form_tag doctor_requests_list_path, method: 'GET' do
  = select_date @filtered_date, prefix: 'filtered_date'
  = submit_tag 'Фильтровать'

table(cellspacing=0 cellpadding=10)
  tr
    th ФИО и дата рождения
    th Отделение
    th Время визита
    th Адрес
    th Телефон
    th Время записи
    th
    th Комментарий
  - @doctor_requests.each do |request|
    tr
      td
        = "#{request.full_name} #{request.birthday.strftime("%d.%m.%Y")}"
      td = request.department_name
      td = request.visit_at.strftime("%d.%m.%Y")
      td = request.address
      td
        = request.phone_number
        - if request.additional_phone_number
          br
          = request.additional_phone_number

      td = request.created_at.strftime("%d.%m.%Y, %H:%M")
      td
        = form_for request, remote: true do |f|
          = f.check_box :called, class: 'js-called-checkbox'
      td
        = form_for request, class: 'js-comment-form' do |f|
          = f.text_area :comment, class: 'js-comment', rows: 2, cols: 30

app/views/doctor_requests/person.slim
.body
  - if @show_districts_info
    .appointment-form
      h2 Вызвать по телефону
      .confirm-box.m-bordered
          .text-row.districts-info
            - @district_collection.each do |info|
              .district-info
                .district-info__title = info.district_title
                .district-info__phone = info.phone

  br
  br

  .appointment-form.js-appointment-step-2
    - if @show_districts_info
      h2 Вызвать онлайн
    = render_doctor_requests_steps_for_step 1

    = error_messages

    = form_tag doctor_requests_hospital_path do
      = render 'hidden_fields'
      .form-group
        h3 Представьтесь, пожалуйста
        p
          | Введите полностью Ваше имя и дату рождения.
          br
          | Все эти поля обязательны для заполнения
        .text-row
          = text_field_tag 'last_name', params[:last_name], size:'40', placeholder: 'Фамилия', required: true
          = text_field_tag 'first_name', params[:first_name], size:'30', placeholder: 'Имя', required: true
          = text_field_tag 'middle_name', params[:middle_name], size:'40', placeholder: 'Отчество'

        .text-row
          = text_field_tag 'birthday(3i)', params['birthday(3i)'], size:'4', placeholder: 'День', required: true, type: 'text', maxlength: 2, class: 'js-numeric'

          / заполняем выбранный месяц
          - unless params[:birthday].blank?
            - if Date.valid_date? *params[:birthday].split('-').map(&:to_i)
              - birthday_month = Date.parse(params[:birthday])
          - else
            - birthday_month = nil
          = select_month birthday_month, { field_name: false, prompt: 'Месяц',  prefix: 'birthday(2i)', discard_type: true }, { class: 'js-requried  js-select', required: true, placeholder: 'месяц' }

          = text_field_tag 'birthday(1i)', params['birthday(1i)'], size:'10', placeholder: 'Год', required: true, type: 'text', maxlength: 4, class: 'js-numeric'

      .btn-block
        = submit_tag 'Далее', class: 'btn btn-success m-inactive js-next-step', disabled: :disabled
        .info Заполните все поля,чтобы перейти к следующему шагу

app/views/doctor_requests/rostovskaya_all_live.html.slim
.body
  .appointment-form.js-appointment-step-6
    .back-btn.js-back-btn

    .col.col-60
      h3 = "Уважаемый #{params[:first_name]} #{params[:middle_name]}"


      .confirm-box
        .form-group
          .text-row
            .info.m-big
              | В&nbsp;связи с&nbsp;большой загруженностью, в&nbsp;центре по&nbsp;адресу Ростовская 14-16, временно, осуществляется прием в&nbsp;режиме &laquo;живой очереди&raquo;.
              br
              |Часы работы центра:будние дни с&nbsp;8:00&nbsp;&mdash; 20:00; выходные и&nbsp;праздничные с&nbsp;9:00&nbsp;&mdash; 17:00

app/views/doctor_requests/success.html.slim
.body
  .appointment-form.js-appointment-step-6
    .back-btn.js-back-btn

    .col.col-60
      h3 = "Уважаемый #{params[:first_name]} #{params[:middle_name]}"


      .confirm-box
        .form-group
          .text-row
            .info.m-big
              | Заявка на вызов врача на дом оформлена. В ближайшее время с Вами свяжется наш оператор и подтвердит данные по вызову.
              br
              | Внимание! Если в течении двух часов после оформления заявки оператор Вам не перезвонил, пожалуйста, обратитесь в сall-центр по номеру 670-00-03.