config/routes.rb
Polisoms::Application.routes.draw do

  match '/search', to: 'search#search'
  

  # match '/choose_district' => 'appointments#choose_district'
  # match '/choose_hospital' => 'appointments#choose_hospital'
  # match '/check_patient' => 'appointments#check_patient'
  # match '/get_speciality_list' => 'appointments#get_speciality_list'
  # match '/get_doctor_list' => 'appointments#get_doctor_list'
  # match '/get_available_dates' => 'appointments#get_available_dates'
  # match '/get_available_appointments' => 'appointments#get_available_appointments'
  # match '/set_appointment' => 'appointments#set_appointment'
  # match '/get_patient_history' => 'appointments#get_patient_history'
  # match '/create_claim_for_refusal' => 'appointments#create_claim_for_refusal'


  scope 'api' do
    # раздел запись к врачу
    get 'districts' => 'api_appointments#districts'
    get 'polyclinics' => 'api_appointments#polyclinics'
    get 'specialities' => 'api_appointments#specialities'
    get 'doctors' => 'api_appointments#doctors'
    # ======================
  end

  namespace :api do
    resources :reviews, only: [:create, :index]
  end



  # публичные страницы с записью к врачу
  get '/appointment/step1' => 'appointments#step1', as: :appointment_step1
  match '/appointment/step2' => 'appointments#step2', as: :appointment_step2
  match '/appointment/step3' => 'appointments#step3', as: :appointment_step3
  match '/appointment/step4' => 'appointments#step4', as: :appointment_step4
  match '/appointment/check' => 'appointments#check', as: :appointment_check
  match '/appointment/confirm' => 'appointments#confirm', as: :appointment_confirm
  match '/appointment/history' => 'appointments#history', as: :appointment_history

  # публичные страницы на отмену записи к врачу
  get '/cancel_appointment/step1' => 'cancel_appointments#step1', as: :cancel_appointment_step1
  match '/cancel_appointment/step2' => 'cancel_appointments#step2', as: :cancel_appointment_step2
  match '/cancel_appointment/history' => 'cancel_appointments#history', as: :cancel_appointment_history
  match '/cancel_appointment/auth' => 'cancel_appointments#passport_auth', as: :cancel_appointment_auth
  match '/cancel_appointment/claim_for_refusal' => 'cancel_appointments#claim_for_refusal', as: :cancel_appointment_claim_for_refusal

  # публичные страницы для вызова врача на дом
  get '/doctor_requests/person' => 'doctor_requests#person', as: :doctor_requests_person
  match '/doctor_requests/hospital' => 'doctor_requests#hospital', as: :doctor_requests_hospital
  match '/doctor_requests/form' => 'doctor_requests#form', as: :doctor_requests_form
  post '/doctor_requests/create' => 'doctor_requests#create', as: :doctor_requests
  get '/doctor_requests/success' => 'doctor_requests#success', as: :doctor_requests_success
  get '/doctor_requests/apology' => 'doctor_requests#apology', as: :doctor_requests_apology
  get '/doctor_requests/rostovskaya_all_live' => 'doctor_requests#all_live', as: :doctor_requests_all_live
  get '/doctor_requests/list' => 'doctor_requests#list', as: :doctor_requests_list
  put '/doctor_requests/:id' => 'doctor_requests#update', as: :doctor_request
  get '/doctor_requests/:check_free_coupons' => 'doctor_requests#check_free_coupons', as: :doctor_request_check_free_coupons


  resources :reviews, only: [:index, :create]
  resources :articles
  
  match '/load_articles' => 'articles#index'
  
  resources :services


  mount Ckeditor::Engine => '/ckeditor'

  resources :abouts

  resources :offices

  # admin area
  ActiveAdmin.routes(self)
  post '/admin/reviews/:id/answer' => 'admin/reviews#answer', as: :admin_review_review_answers
  # =================

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  root :to => 'static_pages#home'
  get 'poll_of_the_year' => 'static_pages#poll_of_the_year', as: :poll_of_the_year
  get 'jci' => 'static_pages#jci', as: :jci
  # страница с марафоном и записью к врачу по 4ое июля
  # get 'runners' => 'static_pages#runners', as: :runners
  get 'polls/:id' => 'static_pages#polls'
  get 'p/:id' => 'static_pages#external_poll', as: :external_poll

  resources :news

  post 'set_region', to: 'application#set_region'
  post 'update_office', to: 'offices#update_pos'

  resources :doctors, only: [:index, :show], as: :staff do
    member do
      post 'like'
    end
  end

  resources :vacancies, only: [:index, :show]
  resource :vacancy_requests, only: [:create]
  resource :visit_requests, only: [:create]
end

app/controllers/cancel_appointments_controller.rb
# encoding: utf-8
class CancelAppointmentsController < ApplicationController
  before_filter :create_appointment, :check_region

  def step1
  end

  def step2
    params.delete(:action)
    @back_path = cancel_appointment_step1_path(params)
  end

  # авторизация по паспорту
  # в случае успеха удаляем данные из общих параметров и редиректим на историю
  def passport_auth
    begin
      init_birthday
      @back_path = cancel_appointment_step1_path(params)
      patient_id = @appointment.check_patient(params[:lpu_id], params[:first_name], params[:last_name], params[:birthday])
      if patient_id.blank?
        flash[:error] = 'Уважаемый Пациент! К сожалению, мы не смогли найти Вас в нашей базе данных. Возможно, Вы никогда ранее не обращались в наши центры, либо же допустили ошибку при вводе информации. Пожалуйста, попробуйте ввести данные снова, либо же обратитесь в наш колл-центр по телефону в Санкт-Петербурге 670 00 03 с 8.00 до 20.00 ежедневно. В период с 11.00 до 16.00 наш колл-центр загружен менее всего.'
        redirect_to @back_path
      else
        params[:patient_id] = patient_id
        lpu_id = params[:lpu_id]
        patient_id = params[:patient_id]
        doc_series = params[:doc_series]
        doc_number = params[:doc_number]
        if doc_series && doc_number
          @confirmation = @appointment.check_patient_by_passport(lpu_id, patient_id, doc_series, doc_number)
          params.delete(:doc_series)
          params.delete(:doc_number)
          params.delete(:action)
          if @confirmation
            redirect_to cancel_appointment_history_path(params)
          else
            flash[:error] = 'Пациент с указанными паспортными данными не найден.'
            redirect_to cancel_appointment_auth_path(params)
          end
        end
      end
    rescue Savon::SOAPFault, ArgumentError, TypeError
      flash[:error] = 'Введенные ранее данные устарели, пожалуйста, начните с начала'
      redirect_to cancel_appointment_step1_path(params)
    end
  end


  # по дизайну нужно взять район и больницу.
  # но судя по документации, этого не взять этим методом
  def history
    params.delete(:action)
    @back_path = cancel_appointment_step2_path(params)
    @history = @appointment.get_patient_history(params[:lpu_id], params[:patient_id])
    @pastHistory = @history.map{ |item| item if item[:visit_start] < DateTime.now }
                       .compact
                       .sort{ |a, b| b[:visit_start] <=> a[:visit_start]}
    @futureHistory = @history.map{ |item| item if item[:visit_start] > DateTime.now }
                         .compact
                         .sort { |a, b| b[:visit_start] <=> a[:visit_start] }
  end

  def claim_for_refusal
    appointment_id = params.delete(:id_appointment)
    result = @appointment.create_claim_for_refusal(params[:lpu_id], params[:patient_id], appointment_id)
    if result.try(:[], 0)[:success]
      flash[:error] = 'Вы успешно отменили запись к врачу'
    else
      flash[:error] = 'При отмене записи произошла ошибка. Пожалуйста, свяжитесь с нами по телефону +7 (812) 670 00 03'
    end
    redirect_to cancel_appointment_history_path(params)
  end

  private

  def create_appointment
    @appointment = Appointment.new
  end


  def init_birthday
    params[:birthday] = unless params['birthday(1i)'].blank? && params['birthday(2i)'].blank? && params['birthday(3i)'].blank?
                          "#{params['birthday(1i)']}-#{params['birthday(2i)']}-#{params['birthday(3i)']}"
                        else
                          nil
                        end
  end


  def init_doctor
    @doctor ||= @appointment.get_doctor_list(params[:speciality_id], params[:lpu_id], params[:patient_id]).select { |d| d[:id_doc] == params[:doctor_id].to_s }.first
  end

  def check_region
    redirect_to root_path unless region_has_appointments
  end

end

app/helpers/cancel_appointments_helper.rb
# coding: utf-8
module CancelAppointmentsHelper


  # рисуем последовательност из 3х шагов
  # и выделем цветом шаг по значению переменной num
  # в методе очень важна последовательность блоков
  # т.к.некоторые методы имеют свойство float
  # для позиционирования на странице
  def render_cancel_steps_for_step num=1

    step1_css = 'm-active' if num >= 1
    step2_css = 'm-active' if num >= 2
    step3_css = 'm-active' if num >= 3

    content_tag(:div, class: 'steps') do
      content_tag(:div, '01. Личные данные', class: "step left #{step1_css}") +
      content_tag(:div, '03. Отмена записи', class: "step right #{step3_css}") +
      content_tag(:div, '02. Выбор отделения', class: "step center #{step2_css}")
    end +
    back_button

  end


  # кнопка «назад»
  def back_button
    content_tag :div, class: 'back-btn js-back-btn' do
      link_to('← Назад', @back_path, class: 'link') if @back_path
    end
  end

  def error_messages
    unless flash[:error].blank?
      content_tag :div, flash[:error], class: 'error'
    end
  end

  private


end

app/views/cancel_appointments/history.html.slim
.body
  .appointment-form.js-appointment-step-3
    = render_cancel_steps_for_step 3

    = error_messages

    .h-group
      h4 = link_to 'Запишитесь на прием', appointment_step3_path(params)
      h3 = '/ Текущие записи'
      p В списке выведены ваши записи. Вы можете удалить любую из них.


    - unless @futureHistory.blank?
      p Предстоящие записи
      table.table cellspacing=0
        tr
          th Доктор
          th Специализация
          th Дата
        - @futureHistory.each do |appointment|
          tr
            td = appointment[:doctor_rending_consultation][:name]
            td = appointment[:speciality_bring_referal][:name_spesiality]
            td.appointment-form__remove-appointment
              span = l appointment[:visit_start], format: "%d %B %Y, %H:%M"
              span.appointment-form__remove-appointment-icon
                = form_tag cancel_appointment_claim_for_refusal_path do
                  | x
                  = render 'appointments/hidden_fields'
                  = hidden_field_tag :id_appointment, appointment[:id_appointment]
                  = submit_tag 'Отменить запись', class: 'appointment-form__remove-appointment-btn', data: { confirm: 'Отменить запись к врачу?' }

    - else
      p У вас нет ни одной предстоящей записи
    br
    br
    br
    br
    / Было решено скрыть историю прошлых записей
    /- unless @pastHistory.blank?
      p Прошедшие записи
      table.table cellspacing=0
        tr
          th Доктор
          th Специализация
          th Дата
        - @pastHistory.each do |appointment|
          tr
            td = appointment[:doctor_rending_consultation][:name]
            td = appointment[:speciality_bring_referal][:name_spesiality]
            td.appointment-form__remove-appointment
              span = l appointment[:visit_start], format: "%d %B %Y, %H:%M"
              span.appointment-form__remove-appointment-icon(style='visibility:hidden')
                | x

    - if @futureHistory.blank? && @pastHistory.blank?
      .error История записей пуста.

app/views/cancel_appointments/passport_auth.html.slim
.body
  .appointment-form.js-appointment-login
    = render_cancel_steps_for_step 2

    = error_messages

    .h-group
      h4 = link_to 'Запишитесь на прием', appointment_step3_path(params)
      h3 = '/ Авторизация'
      p Чтобы просмотреть предстоящие записи необходимо вас авторизовать

    = form_tag cancel_appointment_auth_path do
      = render 'appointments/hidden_fields'
      .form-group
        h3 Паспортные данные
        p Заполните серию и номер вашего паспорта или свидетельства о рождении
        .text-row
          = text_field_tag :doc_series, params[:doc_series], id: 'js-districts', size: '9', maxlength: 6, placeholder: 'Серия', required: true
          = text_field_tag :doc_number, params[:doc_number], id: 'js-districts', size: '11', maxlength: 6, placeholder: 'Номер', required: true

      .btn-block
        = submit_tag 'Далее', class: 'btn btn-success m-inactive js-next-step', disabled: :disabled
        .info Заполните все поля,чтобы перейти к следующему шагу

app/views/cancel_appointments/step1.html.slim
.body
  .appointment-form.js-appointment-step-2
    = render_cancel_steps_for_step 1

    = error_messages

    = form_tag cancel_appointment_step2_path do
      = render 'appointments/step1_form'

app/views/cancel_appointments/step2.html.slim
.body
  .appointment-form.js-appointment-step-1
    = render_cancel_steps_for_step 2

    = error_messages

    = form_tag cancel_appointment_auth_path do
      = render 'appointments/step2_form'